"""create users table

Revision ID: 3b71e3ec2df9
Revises: 1cf7ed38ede2
Create Date: 2024-06-26 17:58:17.229052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b71e3ec2df9'
down_revision: Union[str, None] = '1cf7ed38ede2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
